@baseUrl = https://api.event.matheusfelipe.dev/api

@tokenValue = {{authenticate.response.body.token}}
@tokenType = {{authenticate.response.body.token_type}}

@authToken = {{tokenType}} {{tokenValue}}


# @name authenticate
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email":"teste@teste.com",
    "password":"12345678"
}


### Rota para fazer cadastro
POST {{baseUrl}}/signup
Content-Type: application/json

{
  "name": "Teste",
  "cpf": "12345",
  "email": "teste@teste.com",
  "password": "12345678",
  "password_confirmation": "12345678"
}